apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rd6syf46n-python 
  janus-idp.io/tekton: rd6syf46n-python
  backstage.io/kubernetes-id: rd6syf46n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rd6syf46n-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  