apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rd6syf46n-python-gitops
  description: This is GitOps manifest for rd6syf46n-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rd6syf46n-python
    backstage.io/kubernetes-id: rd6syf46n-python 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: rd6syf46n-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rd6syf46n-python
